defaults:
  - object: default

object:
  text_margin: 60
  width: 50
  height: 50
  text_size: 30
  rounding_size: 10

receptacle:
  horizontal_margin: 5
  target_height: 200
  placeholder:
    width: 50
    height: 50
    rounding_size: 10
  placeholder_margin: 40

room:
  placeholder:
    width: 50
    height: 50
    rounding_size: 10
  box_alpha: 1.0
  horizontal_margin: 10
  vertical_margin: 10
  top_pad: 10
  bottom_pad: 100
  left_pad: 50
  right_pad: 50
  full_height: 600
  half_height: 300
  objects_height: 500
  min_width: 100
  object_horizontal_margin_fraction: 0.15 # Fraction on each side to skip
  text_size: 30
  border_width: 10

scene:
  arrow:
    head_length: 25
    head_width: 50
    linewidth: 2
    overhang: 0.9
  target_width: 4000
  instruction_text_size: 45
